services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
